### PR TITLE
Updated header style to improve legibility

### PR DESCRIPTION
**Pull request by mttmccb**
Just done it on the desktop sizes for now, haven't really looked at below the header yet.

### CODE REVIEW

**Comment by stephlocke** [comment]
I'm getting issues with the CSS sheets not loading - you've added versions in. Is that because they're in a latest update to the hugo-agency-theme?

**Comment by stephlocke** [comment]
When it builds a site, it pulls the css out of the subfolders: https://github.com/stephlocke/battleofthebeards/tree/master/public/css

**Comment by mttmccb** [comment]
Yeah, the header is different, a few of the files gave 404s until it was updated

**Comment by stephlocke** [comment]
Yeah, locally however you were doing it, but when hugo is run the files get added into public with a versionless structure so they don't load up when I run it, and it wouldn't work when the public version is deployed.

I'm leaving for NDC in half an hour but if you've got time for a quick screen share and convo we can try and sort this out a bit quicker on https://appear.in/battleofthebeards

**Comment by mttmccb** [comment]
Sorry just saw the message, it's basically the reverse of what I'm seeing then, works locally but not online :) Enjoy NDC!

I'll have a poke around, but I have a feeling it's something to do with different versions of the theme and hugo.

**Comment by mttmccb** [comment]
Sorry it took so long to get back to this but I got it working with the version of the theme you're using I just had to get theme this way

```shell
cd themes
git clone https://github.com/digitalcraftsman/hugo-agency-theme
cd hugo-agency-theme
git checkout 4f504cf
```

I guess the theme had some breaking changes.

**Pull request merged**
